### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by askonivala** [COMHIS/bibliographica#16]
install_github("ropengov/bibliographica") results in:

ERROR: dependency 'genderdata' is not available for package 'bibliographica'

**Comment by villevaara** [comment]
You need to install genderdata separately - install_github("ropensci/genderdata")

Might be true for some other dependencies also.

**Comment by antagomir** [comment]
Also note installatio command is nowadays install_github("COMHIS/bibliographica")

**Comment by askonivala** [comment]
Thanks a lot. I was now able to install the package correctly and we can close the issue. But I would recommend updating the [installation instructions](https://github.com/COMHIS/bibliographica/blob/master/vignettes/tutorial.md) to include the dependency on genderdata and point to the new repository as well.

**Comment by antagomir** [comment]
Yes, thanks. This would become more critical if/when the package will be intended for more general use. That is not the case atm. It is far too experimental & unstable.
